#!/usr/bin/env python3
"""Assemble dist/ — the set of files that are allowed to be public — and nothing else.

WHY THIS EXISTS
---------------
The site used to deploy with `wrangler pages deploy .` straight from the repo
root. Cloudflare Pages uploads every file it is given, so that published the
entire working tree: a full unpublished book manuscript, every future-dated
draft post, build.py, and the internal working notes were all fetchable in
production. Nobody had to guess a URL — /BOOK_still-normal-manuscript.md just
returned 200.

`.assetsignore` does NOT fix this. It is a Workers-assets feature; the
`wrangler pages deploy` code path ignores it entirely. That was verified against
wrangler 4.120.0 by deploying with one in place and watching the excluded files
come back 200.

So the deploy is an ALLOWLIST, and it lives here. A file reaches production only
if a rule below names it. The failure mode of a denylist is silent and permanent
— you add a new manuscript, forget to exclude it, and it is public until someone
notices. The failure mode of an allowlist is a missing page, which is loud and
obvious and gets fixed in minutes.

USAGE
-----
    python3 build.py            # render posts/*.md -> blog/*.html first
    python3 stage-deploy.py     # assemble dist/
    npx wrangler@4 pages deploy dist --project-name doctorarchers-site --branch main

Or just run the whole thing:

    python3 stage-deploy.py --deploy

ADDING A PAGE: new .html at the repo root or in blog/ is picked up automatically.
Anything else — a new directory, a PDF, a font — needs a rule in ALLOW below.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"

PROJECT = "doctorarchers-site"
ACCOUNT_ID = "1d18bf879817a7681e338e3682580a87"

# ---------------------------------------------------------------------------
# The allowlist. Globs are relative to the repo root.
# ---------------------------------------------------------------------------
ALLOW = [
    "*.html",           # every hand-written page, incl. 404.html
    "blog/*.html",      # generated by build.py from posts/*.md
    "assets/**/*",      # images, css, downloadable PDFs
    "functions/**/*.js",  # Pages Functions (contact form, apex/www redirect)
    "_headers",
    "_redirects",
    # Which paths invoke Functions. Without this, adding functions/_middleware.js
    # would put a Worker in front of every image and stylesheet on the site.
    "_routes.json",
    "robots.txt",
    "sitemap.xml",
    "llms.txt",
]

# ---------------------------------------------------------------------------
# Carve-outs from the allowlist above. These match paths the globs would
# otherwise sweep in. Keep each one commented — a rule nobody understands is a
# rule someone deletes.
# ---------------------------------------------------------------------------
DENY = [
    # Editor backup left in the tree; it is a stale copy of a live page and
    # would be served as its own indexable URL.
    "*.bak*",

    # Drafts. Both exist in the working tree, neither is linked from anywhere,
    # and both were 404 in production until a deploy published them by accident.
    # To publish one: delete its line here AND link to it from a real page in
    # the same change, so it does not become another orphan.
    "glp1-updates.html",
    "blog/why-glp1-stops-working.html",

    # Setup notes that live beside the Pages Function.
    "functions/**/*.md",
]

# Files that must exist in dist/ or the deploy is wrong. Cheap insurance against
# a glob that silently stops matching.
REQUIRED = [
    "index.html",
    "404.html",
    "robots.txt",
    "sitemap.xml",
    "llms.txt",
    "assets/styles.css",
    "blog/index.html",
    "_headers",
    # If _routes.json goes missing, Pages falls back to auto-generated routes
    # and _middleware.js starts running on every asset request. The site still
    # works, so nothing would look wrong — it would just quietly burn a Worker
    # invocation per image.
    "_routes.json",
    "functions/_middleware.js",
]


def matches(path: Path, patterns: list[str]) -> bool:
    rel = path.relative_to(ROOT).as_posix()
    for pat in patterns:
        if path.relative_to(ROOT).match(pat) or Path(rel).match(pat):
            return True
        # Path.match anchors to the right; make "assets/**/*" behave as a prefix.
        if pat.endswith("/**/*") and rel.startswith(pat[: -len("/**/*")] + "/"):
            return True
    return False


def collect() -> list[Path]:
    seen: set[Path] = set()
    for pat in ALLOW:
        for p in ROOT.glob(pat):
            if p.is_file():
                seen.add(p)
    return sorted(f for f in seen if not matches(f, DENY))


def stage() -> list[Path]:
    if DIST.exists():
        shutil.rmtree(DIST)
    files = collect()
    for src in files:
        dst = DIST / src.relative_to(ROOT)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    missing = [r for r in REQUIRED if not (DIST / r).exists()]
    if missing:
        sys.exit(
            "stage-deploy: refusing to deploy, these required files are missing "
            "from dist/:\n  " + "\n  ".join(missing) +
            "\nA glob in ALLOW probably stopped matching. Fix it before deploying."
        )
    return files


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--deploy", action="store_true",
                    help="run wrangler against dist/ after staging")
    args = ap.parse_args()

    files = stage()
    total = sum(f.stat().st_size for f in files)
    html = sum(1 for f in files if f.suffix == ".html")
    print(f"staged {len(files)} files ({total/1024:.0f} KB) into dist/ — {html} pages")

    excluded = [
        p for p in ROOT.rglob("*")
        if p.is_file()
        and not p.relative_to(ROOT).as_posix().startswith(
            (".git/", "dist/", ".claude/", ".wrangler/", "node_modules/"))
        and p not in set(files)
    ]
    print(f"held back {len(excluded)} files that will NOT be public "
          f"(manuscripts, post sources, build tooling, notes)")

    if not args.deploy:
        print("\nnot deployed. To publish:\n"
              f"  npx wrangler@4 pages deploy dist --project-name {PROJECT} --branch main")
        return

    env = {**os.environ, "CLOUDFLARE_ACCOUNT_ID": ACCOUNT_ID}
    subprocess.run(
        ["npx", "--yes", "wrangler@4", "pages", "deploy", "dist",
         "--project-name", PROJECT, "--branch", "main", "--commit-dirty=true"],
        cwd=ROOT, env=env, check=True,
    )


if __name__ == "__main__":
    main()
